// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: sysinfodm.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatsType    string `protobuf:"bytes,1,opt,name=stats_type,json=statsType,proto3" json:"stats_type,omitempty"`
	SecondsDelay int32  `protobuf:"varint,2,opt,name=seconds_delay,json=secondsDelay,proto3" json:"seconds_delay,omitempty"`
	SecondsRange int32  `protobuf:"varint,3,opt,name=seconds_range,json=secondsRange,proto3" json:"seconds_range,omitempty"`
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sysinfodm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sysinfodm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_sysinfodm_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetStatsType() string {
	if x != nil {
		return x.StatsType
	}
	return ""
}

func (x *StreamRequest) GetSecondsDelay() int32 {
	if x != nil {
		return x.SecondsDelay
	}
	return 0
}

func (x *StreamRequest) GetSecondsRange() int32 {
	if x != nil {
		return x.SecondsRange
	}
	return 0
}

type CPUStat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sys    float32 `protobuf:"fixed32,1,opt,name=sys,proto3" json:"sys,omitempty"`
	Usr    float32 `protobuf:"fixed32,2,opt,name=usr,proto3" json:"usr,omitempty"`
	Idle   float32 `protobuf:"fixed32,3,opt,name=idle,proto3" json:"idle,omitempty"`
	Iowait float32 `protobuf:"fixed32,4,opt,name=iowait,proto3" json:"iowait,omitempty"`
}

func (x *CPUStat) Reset() {
	*x = CPUStat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sysinfodm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CPUStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUStat) ProtoMessage() {}

func (x *CPUStat) ProtoReflect() protoreflect.Message {
	mi := &file_sysinfodm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUStat.ProtoReflect.Descriptor instead.
func (*CPUStat) Descriptor() ([]byte, []int) {
	return file_sysinfodm_proto_rawDescGZIP(), []int{1}
}

func (x *CPUStat) GetSys() float32 {
	if x != nil {
		return x.Sys
	}
	return 0
}

func (x *CPUStat) GetUsr() float32 {
	if x != nil {
		return x.Usr
	}
	return 0
}

func (x *CPUStat) GetIdle() float32 {
	if x != nil {
		return x.Idle
	}
	return 0
}

func (x *CPUStat) GetIowait() float32 {
	if x != nil {
		return x.Iowait
	}
	return 0
}

type LAStat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	La1  float32 `protobuf:"fixed32,1,opt,name=la1,proto3" json:"la1,omitempty"`
	La5  float32 `protobuf:"fixed32,2,opt,name=la5,proto3" json:"la5,omitempty"`
	La15 float32 `protobuf:"fixed32,3,opt,name=la15,proto3" json:"la15,omitempty"`
}

func (x *LAStat) Reset() {
	*x = LAStat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sysinfodm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LAStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LAStat) ProtoMessage() {}

func (x *LAStat) ProtoReflect() protoreflect.Message {
	mi := &file_sysinfodm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LAStat.ProtoReflect.Descriptor instead.
func (*LAStat) Descriptor() ([]byte, []int) {
	return file_sysinfodm_proto_rawDescGZIP(), []int{2}
}

func (x *LAStat) GetLa1() float32 {
	if x != nil {
		return x.La1
	}
	return 0
}

func (x *LAStat) GetLa5() float32 {
	if x != nil {
		return x.La5
	}
	return 0
}

func (x *LAStat) GetLa15() float32 {
	if x != nil {
		return x.La15
	}
	return 0
}

type DiskInfoStat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tps float32 `protobuf:"fixed32,1,opt,name=tps,proto3" json:"tps,omitempty"`
	Kbs float32 `protobuf:"fixed32,2,opt,name=kbs,proto3" json:"kbs,omitempty"`
}

func (x *DiskInfoStat) Reset() {
	*x = DiskInfoStat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sysinfodm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiskInfoStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskInfoStat) ProtoMessage() {}

func (x *DiskInfoStat) ProtoReflect() protoreflect.Message {
	mi := &file_sysinfodm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskInfoStat.ProtoReflect.Descriptor instead.
func (*DiskInfoStat) Descriptor() ([]byte, []int) {
	return file_sysinfodm_proto_rawDescGZIP(), []int{3}
}

func (x *DiskInfoStat) GetTps() float32 {
	if x != nil {
		return x.Tps
	}
	return 0
}

func (x *DiskInfoStat) GetKbs() float32 {
	if x != nil {
		return x.Kbs
	}
	return 0
}

type DiskStat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DiskStat map[string]*DiskInfoStat `protobuf:"bytes,1,rep,name=disk_stat,json=diskStat,proto3" json:"disk_stat,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *DiskStat) Reset() {
	*x = DiskStat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sysinfodm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiskStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskStat) ProtoMessage() {}

func (x *DiskStat) ProtoReflect() protoreflect.Message {
	mi := &file_sysinfodm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskStat.ProtoReflect.Descriptor instead.
func (*DiskStat) Descriptor() ([]byte, []int) {
	return file_sysinfodm_proto_rawDescGZIP(), []int{4}
}

func (x *DiskStat) GetDiskStat() map[string]*DiskInfoStat {
	if x != nil {
		return x.DiskStat
	}
	return nil
}

type StatsResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Stat:
	//	*StatsResponce_CpuStats
	//	*StatsResponce_LaStats
	//	*StatsResponce_DiskInfo
	Stat isStatsResponce_Stat `protobuf_oneof:"stat"`
}

func (x *StatsResponce) Reset() {
	*x = StatsResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sysinfodm_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatsResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponce) ProtoMessage() {}

func (x *StatsResponce) ProtoReflect() protoreflect.Message {
	mi := &file_sysinfodm_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponce.ProtoReflect.Descriptor instead.
func (*StatsResponce) Descriptor() ([]byte, []int) {
	return file_sysinfodm_proto_rawDescGZIP(), []int{5}
}

func (m *StatsResponce) GetStat() isStatsResponce_Stat {
	if m != nil {
		return m.Stat
	}
	return nil
}

func (x *StatsResponce) GetCpuStats() *CPUStat {
	if x, ok := x.GetStat().(*StatsResponce_CpuStats); ok {
		return x.CpuStats
	}
	return nil
}

func (x *StatsResponce) GetLaStats() *LAStat {
	if x, ok := x.GetStat().(*StatsResponce_LaStats); ok {
		return x.LaStats
	}
	return nil
}

func (x *StatsResponce) GetDiskInfo() *DiskStat {
	if x, ok := x.GetStat().(*StatsResponce_DiskInfo); ok {
		return x.DiskInfo
	}
	return nil
}

type isStatsResponce_Stat interface {
	isStatsResponce_Stat()
}

type StatsResponce_CpuStats struct {
	CpuStats *CPUStat `protobuf:"bytes,1,opt,name=cpu_stats,json=cpuStats,proto3,oneof"`
}

type StatsResponce_LaStats struct {
	LaStats *LAStat `protobuf:"bytes,2,opt,name=la_stats,json=laStats,proto3,oneof"`
}

type StatsResponce_DiskInfo struct {
	DiskInfo *DiskStat `protobuf:"bytes,3,opt,name=disk_info,json=diskInfo,proto3,oneof"`
}

func (*StatsResponce_CpuStats) isStatsResponce_Stat() {}

func (*StatsResponce_LaStats) isStatsResponce_Stat() {}

func (*StatsResponce_DiskInfo) isStatsResponce_Stat() {}

var File_sysinfodm_proto protoreflect.FileDescriptor

var file_sysinfodm_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x79, 0x73, 0x69, 0x6e, 0x66, 0x6f, 0x64, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x73, 0x79, 0x73, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x22, 0x78, 0x0a, 0x0d,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x74, 0x61, 0x74, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x0d,
	0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x5f, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x44, 0x65, 0x6c, 0x61,
	0x79, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x5f, 0x72, 0x61, 0x6e,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x73, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x22, 0x59, 0x0a, 0x07, 0x43, 0x50, 0x55, 0x53, 0x74, 0x61,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x79, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03,
	0x73, 0x79, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x73, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x03, 0x75, 0x73, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x64, 0x6c, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x04, 0x69, 0x64, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6f, 0x77,
	0x61, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x69, 0x6f, 0x77, 0x61, 0x69,
	0x74, 0x22, 0x40, 0x0a, 0x06, 0x4c, 0x41, 0x53, 0x74, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c,
	0x61, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6c, 0x61, 0x31, 0x12, 0x10, 0x0a,
	0x03, 0x6c, 0x61, 0x35, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6c, 0x61, 0x35, 0x12,
	0x12, 0x0a, 0x04, 0x6c, 0x61, 0x31, 0x35, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x6c,
	0x61, 0x31, 0x35, 0x22, 0x32, 0x0a, 0x0c, 0x44, 0x69, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x53,
	0x74, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x70, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x03, 0x74, 0x70, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x62, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x03, 0x6b, 0x62, 0x73, 0x22, 0xa0, 0x01, 0x0a, 0x08, 0x44, 0x69, 0x73, 0x6b,
	0x53, 0x74, 0x61, 0x74, 0x12, 0x3e, 0x0a, 0x09, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x73, 0x79, 0x73, 0x64, 0x61, 0x65,
	0x6d, 0x6f, 0x6e, 0x2e, 0x44, 0x69, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x2e, 0x44, 0x69, 0x73,
	0x6b, 0x53, 0x74, 0x61, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x64, 0x69, 0x73, 0x6b,
	0x53, 0x74, 0x61, 0x74, 0x1a, 0x54, 0x0a, 0x0d, 0x44, 0x69, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2d, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x79, 0x73, 0x64, 0x61, 0x65, 0x6d,
	0x6f, 0x6e, 0x2e, 0x44, 0x69, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x53, 0x74, 0x61, 0x74, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xae, 0x01, 0x0a, 0x0d, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x09,
	0x63, 0x70, 0x75, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x73, 0x79, 0x73, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x50, 0x55, 0x53,
	0x74, 0x61, 0x74, 0x48, 0x00, 0x52, 0x08, 0x63, 0x70, 0x75, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12,
	0x2e, 0x0a, 0x08, 0x6c, 0x61, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x73, 0x79, 0x73, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x4c, 0x41,
	0x53, 0x74, 0x61, 0x74, 0x48, 0x00, 0x52, 0x07, 0x6c, 0x61, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12,
	0x32, 0x0a, 0x09, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x79, 0x73, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x44,
	0x69, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x48, 0x00, 0x52, 0x08, 0x64, 0x69, 0x73, 0x6b, 0x49,
	0x6e, 0x66, 0x6f, 0x42, 0x06, 0x0a, 0x04, 0x73, 0x74, 0x61, 0x74, 0x32, 0x54, 0x0a, 0x06, 0x44,
	0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x12, 0x4a, 0x0a, 0x10, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x18, 0x2e, 0x73, 0x79, 0x73, 0x64,
	0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x73, 0x79, 0x73, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x22, 0x00, 0x30,
	0x01, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_sysinfodm_proto_rawDescOnce sync.Once
	file_sysinfodm_proto_rawDescData = file_sysinfodm_proto_rawDesc
)

func file_sysinfodm_proto_rawDescGZIP() []byte {
	file_sysinfodm_proto_rawDescOnce.Do(func() {
		file_sysinfodm_proto_rawDescData = protoimpl.X.CompressGZIP(file_sysinfodm_proto_rawDescData)
	})
	return file_sysinfodm_proto_rawDescData
}

var file_sysinfodm_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sysinfodm_proto_goTypes = []interface{}{
	(*StreamRequest)(nil), // 0: sysdaemon.StreamRequest
	(*CPUStat)(nil),       // 1: sysdaemon.CPUStat
	(*LAStat)(nil),        // 2: sysdaemon.LAStat
	(*DiskInfoStat)(nil),  // 3: sysdaemon.DiskInfoStat
	(*DiskStat)(nil),      // 4: sysdaemon.DiskStat
	(*StatsResponce)(nil), // 5: sysdaemon.StatsResponce
	nil,                   // 6: sysdaemon.DiskStat.DiskStatEntry
}
var file_sysinfodm_proto_depIdxs = []int32{
	6, // 0: sysdaemon.DiskStat.disk_stat:type_name -> sysdaemon.DiskStat.DiskStatEntry
	1, // 1: sysdaemon.StatsResponce.cpu_stats:type_name -> sysdaemon.CPUStat
	2, // 2: sysdaemon.StatsResponce.la_stats:type_name -> sysdaemon.LAStat
	4, // 3: sysdaemon.StatsResponce.disk_info:type_name -> sysdaemon.DiskStat
	3, // 4: sysdaemon.DiskStat.DiskStatEntry.value:type_name -> sysdaemon.DiskInfoStat
	0, // 5: sysdaemon.Daemon.EnableStatStream:input_type -> sysdaemon.StreamRequest
	5, // 6: sysdaemon.Daemon.EnableStatStream:output_type -> sysdaemon.StatsResponce
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_sysinfodm_proto_init() }
func file_sysinfodm_proto_init() {
	if File_sysinfodm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sysinfodm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sysinfodm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CPUStat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sysinfodm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LAStat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sysinfodm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiskInfoStat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sysinfodm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiskStat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sysinfodm_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatsResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_sysinfodm_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*StatsResponce_CpuStats)(nil),
		(*StatsResponce_LaStats)(nil),
		(*StatsResponce_DiskInfo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sysinfodm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sysinfodm_proto_goTypes,
		DependencyIndexes: file_sysinfodm_proto_depIdxs,
		MessageInfos:      file_sysinfodm_proto_msgTypes,
	}.Build()
	File_sysinfodm_proto = out.File
	file_sysinfodm_proto_rawDesc = nil
	file_sysinfodm_proto_goTypes = nil
	file_sysinfodm_proto_depIdxs = nil
}
